import express from "express";
import https from "https";
import fs from "fs";
import cors from "cors";
import dotenv from "dotenv";
import { sendApprovalEmail } from "./sendEmail.js";

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

const PORT = 3001;

// ✅ Simple test route
app.get("/", (req, res) => {
  res.send("🚀 Secure Email Server is running over HTTPS!");
});

// ✅ Email route
app.post("/api/send-email", async (req, res) => {
  const { to, tempPassword } = req.body;
  try {
    await sendApprovalEmail(to, tempPassword);
    res.json({ success: true, message: "Email sent successfully" });
  } catch (error) {
    console.error("Error sending email:", error);
    res.status(500).json({ success: false, error: "Failed to send email" });
  }
});

// ✅ Load SSL certificate and key generated by mkcert
const sslOptions = {
  key: fs.readFileSync("./localhost+1-key.pem"),
  cert: fs.readFileSync("./localhost+1.pem"),
};

// ✅ Create HTTPS server
https.createServer(sslOptions, app).listen(PORT, () => {
  console.log(`✅ HTTPS server running on https://192.168.254.188:${PORT}`);
});
